### ISSUE TITLE
Add a revenue-based trial period

### ISSUE THREAD

**Issue by skorokithakis** [licensezero/prosperity-public-license#6]
I briefly thought of licensing my software under this license, but then realized that I wouldn't use any software that uses it, so I didn't either. The reason is that the time-based trial is too restrictive for my purpose, which is small projects that will barely ever make their hosting costs, let alone profit.

I would like small companies or hobbyist developers to be able to use my software for that purpose, so a better trial period would be revenue-based: You may freely use the software until your company's annual revenues hit $X00,000, and then you must pay. Any changes you make to the software at any point must be shared with the authors (I'm not sure if this is currently a term).

Have you considered this? It seems great to me, both for getting developers paid (by companies who can actually afford it) and for growing their user base (because you aren't preventing customers who can't pay from using the software).

**Comment by kemitchell** [comment]
[PolyForm's Small Business license](https://polyformproject.org/licenses/small-business/1.0.0/) implements a free license for companies that come under stated headcount and annual-revenue figures.

**Comment by skorokithakis** [comment]
I was hoping for a bit more discussion, actually. Why do you feel that a time-limited trial is a better option than revenue limits, for example?
